name: Cleanup Container Registry

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  cleanup-odr-padenc:
    name: Delete untagged odr-padenc images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete untagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'odr-padenc'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 0

  cleanup-odr-dabmux:
    name: Delete untagged odr-dabmux images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete untagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'odr-dabmux'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 0

  cleanup-odr-audioenc-minimal:
    name: Delete untagged odr-audioenc-minimal images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete untagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'odr-audioenc-minimal'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 0

  cleanup-odr-audioenc-full:
    name: Delete untagged odr-audioenc-full images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete untagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'odr-audioenc-full'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 0
